name: Trivy Scanner

on:
  workflow_call:
    
permissions:
  contents: read

jobs:
  scan:
    name: Code scanner
    permissions:
      contents: read
      security-events: write
      actions: read
    uses: fabianomartinsrj/trivy-scan-sample/.github/workflows/trivy.yaml@main

  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build and scan container image
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy container image scanner
        uses: aquasecurity/trivy-action@0.15.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'          
